CRITICAL - 2022-04-30 18:58:38 --> Class "App\Controllers\API\ClienteModel" not found
#0 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(809): App\Controllers\API\Clientes->__construct()
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-04-30 19:02:39 --> Class "App\Controllers\API\ClienteModel" not found
#0 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(809): App\Controllers\API\Clientes->__construct()
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-04-30 19:02:42 --> Class "App\Controllers\API\ClienteModel" not found
#0 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(809): App\Controllers\API\Clientes->__construct()
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-04-30 19:02:55 --> Class "App\Controllers\API\ClienteModel" not found
#0 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(809): App\Controllers\API\Clientes->__construct()
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2022-04-30 19:04:10 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-04-30 19:04:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\API-REST\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\API-REST\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\API-REST\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\API-REST\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#6 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#7 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-30 19:04:14 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-04-30 19:04:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\API-REST\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\API-REST\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\API-REST\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\API-REST\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#6 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#7 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-30 19:04:28 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-04-30 19:04:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\API-REST\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\API-REST\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\API-REST\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\API-REST\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#6 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#7 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-30 19:04:34 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-04-30 19:04:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\API-REST\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\API-REST\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\API-REST\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\API-REST\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#6 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#7 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-30 19:05:42 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-04-30 19:05:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\API-REST\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\API-REST\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\API-REST\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\API-REST\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#6 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#7 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-30 19:06:42 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-04-30 19:06:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\API-REST\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\API-REST\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\API-REST\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\API-REST\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#6 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#7 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-04-30 19:10:01 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-04-30 19:10:01 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\API-REST\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\API-REST\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\API-REST\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\API-REST\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#6 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#7 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-04-30 22:12:11 --> Undefined variable $cliente
#0 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 15)
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#3 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-04-30 22:12:18 --> Undefined variable $cliente
#0 C:\xampp\htdocs\API-REST\app\Controllers\API\Clientes.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 15)
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->index()
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#3 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-04-30 23:00:37 --> Attempt to assign property "id" on null
#0 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->delete('1')
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-04-30 23:04:34 --> Attempt to assign property "id" on null
#0 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->delete('3')
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-04-30 23:08:55 --> Attempt to assign property "id" on null
#0 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(832): App\Controllers\API\Clientes->delete('4')
#1 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Clientes))
#2 C:\xampp\htdocs\API-REST\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\API-REST\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\API-REST\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
